import { ThemeProvider } from '@/components/ThemeProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Mukta } from 'next/font/google'
import { Navbar } from '@/components/Navbar'

const font = Mukta({ weight: "400", subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={font.className}>
      <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <Navbar />
        {children}
      </ThemeProvider>
      </body>
    </html>
  )
}
